### ISSUE TITLE
SQL error when paginate after search on Laravel v5.1.9+

### ISSUE THREAD

**Issue by laitedliang** [nicolaslopezj/searchable#73] opened 2015-08-13 08:44 UTC
Hi,

I got this error when I perform paginate on Laravel version 5.1.9 and above:

```
QueryException in Connection.php line 636:
SQLSTATE[HY000]: General error: 2031 (SQL: select count(*) as aggregate from (select ....
```

My code: 

``` php
user::search('John', null, true)->paginate(10);
```

This error does not occur on normal get()

``` php
user::search('John', null, true)->get() // no error;
```

It also does not occur on Laravel v5.1.8 and below

**Comment by NgYueHong** [comment] 2015-08-13 09:29
+1 Me too facing the same issue... Hope to see the solution for it soon.

**Comment by antekk** [comment] 2015-08-22 08:18
+1 same issue. Thank you for looking at it in advance.

**Comment by zorx** [comment] 2015-08-22 15:49
+1 same issus.

**Comment by stanwarri** [comment] 2015-08-22 17:53
+1 on this issue. Need to find a fix

**Comment by kingsloi** [comment] 2015-08-23 13:22
+1 I get the same issue. 

FYI, MySQL error code 2031:
>  Error: 2031 (CR_PARAMS_NOT_BOUND)
> 
> Message: No data supplied for parameters in prepared statement
https://dev.mysql.com/doc/refman/5.5/en/error-messages-client.html

**Comment by slickorange** [comment] 2015-08-27 08:51
+1

**Comment by Lakshanz** [comment] 2015-08-28 09:34
+1 get the same

**Comment by miharbi** [comment] 2015-08-29 17:11
QueryException in Connection.php line 636:
SQLSTATE[HY093]: Invalid parameter number (SQL: select count(*)

**Comment by mul14** [comment] 2015-08-31 02:40
Weird. As 5.1 LTS version, Laravel should keep the backward compatibility.

Btw, maybe because of this commit on 5.1.9 https://github.com/laravel/framework/commit/ff8b43e4400b8e277eeadbbbc3c0e50a018b90a8.

**Comment by arafatx** [comment] 2015-09-01 05:52
no fix yet?

**Comment by NgYueHong** [comment] 2015-09-01 06:05
@mul14 Yes, I totally agree with you. Maybe we should report this to Laravel as well.

**Comment by svrnm** [comment] 2015-09-08 09:27
Actually the problem is laravel/framework@4c48912

**Comment by wunc** [comment] 2015-09-11 14:54
+1 Anyone have a workaround? (other than restricting Laravel to version 5.1.8)

**Comment by wunc** [comment] 2015-09-11 18:43
So my workaround for now is to use a manual Paginator, which works, but is not as clean and nice as just calling `->paginate()` on the Eloquent query.

Before:
```php
$result = MyModel::search($search_query, $search_threshold)->paginate(10);
```

Manual pagination:
```php
$result = MyModel::search($search_query, $search_threshold)->get();
$limit = 10;
$page = $request->has('page') ? $request->page - 1 : 0;
$total = $result->count();
$result = $result->slice($page * $limit, $limit);
$result = new \Illuminate\Pagination\LengthAwarePaginator($result, $total, $limit);
$result->setPath('/search')->appends(['q' => $search_query]);
```

Of course, this doesn't solve the underlying problem. Just posting how I'm dealing with it for now in case others want to do the same. I also had to change my search form and route to use GET instead of POST.

**Comment by mydnic** [comment] 2015-09-18 08:27
```
QueryException in Connection.php line 636:
SQLSTATE[HY093]: Invalid parameter number
```

Any fix yet ?

**Comment by rene-springmann** [comment] 2015-09-18 08:51
+1 Same Error here

**Comment by zawilliams** [comment] 2015-09-22 05:55
+1

**Comment by lasseal** [comment] 2015-09-22 07:25
+1

**Comment by AbdullahGhanem** [comment] 2015-09-26 01:59
+1

**Comment by Hyleeh** [comment] 2015-09-27 23:53
+1

**Comment by Dzorogh** [comment] 2015-09-29 04:20
+1

**Comment by ShadowD** [comment] 2015-10-01 14:31
+1

**Comment by ShadowD** [comment] 2015-10-02 11:41
Problem is in: vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:~1454

Metod: $this->backupFieldsForCount();

Code:
    protected function backupFieldsForCount()
    {
        foreach (['orders', 'limit', 'offset', 'columns'] as $field) {
            $this->backups[$field] = $this->{$field};

            $this->{$field} = null;
        }

        foreach (['order', 'select'] as $key) {
            $this->bindingBackups[$key] = $this->bindings[$key];

            $this->bindings[$key] = [];
        }
    }

**Comment by rigobcastro** [comment] 2015-10-10 15:12
```
SQLSTATE[HY093]: Invalid parameter number
```

With paginate.

**Comment by ShadowD** [comment] 2015-10-10 18:02
@rigobcastro You use my hotfix?

**Comment by davidbarker** [comment] 2015-10-18 23:20
+1

**Comment by johnRivs** [comment] 2015-10-21 01:54
+1

**Comment by thoughts1053** [comment] 2015-10-22 22:45
Same issue. Simple pagination works at least.

**Comment by rigobcastro** [comment] 2015-10-23 11:26
@ShadowD I didn't. I don't like modify the core. Thanks anyway

**Comment by ShadowD** [comment] 2015-10-23 12:03
I do not like to modify the core.

I have an idea how to fix this problem without modification laravel. Unfortunately, we do not have the time.

**Comment by NgYueHong** [comment] 2015-10-23 12:52
@nicolaslopezj This issue has come to over 30 comments with lots of people facing the problem. It is the most commented issue in this repository. Really hope you can pay attention to this and have a fix for it soon. Thank you.

**Comment by rigobcastro** [comment] 2015-10-23 23:41
@ShadowD I know, thanks again for your solution. @nicolaslopezj Te estamos esperando...

**Comment by woodytang** [comment] 2015-10-25 06:33
Very frustrated problem, experienced it when it was 4.2. For those who want to have a temporary  solution, here is a quick fix:

the problem comes from :Illuminate\Database\Eloquent\Builder::paginate()
``$total = $this->query->getCountForPagination();``
I don't know and don't care whether it was $this->query or getCountForPagination() that goes wrong, what I am gonna do is to simply overwrite this value($total), then everything goes right.

Step 1:
extend Illuminate\Database\Eloquent\Builder;

add a paginate_search() function like this:
```
public function paginate_search($perPage = null,$total, $columns = ['*'], $pageName = 'page', $page = null)
    {
        $this->query->forPage(
            $page = $page ?: Paginator::resolveCurrentPage($pageName),
            $perPage = $perPage ?: $this->model->getPerPage()
        );

        return new LengthAwarePaginator($this->get($columns), $total, $perPage, $page, [
            'path' => Paginator::resolveCurrentPath(),
            'pageName' => $pageName,
        ]);
    }
```

Step 2
In your model, say, Post, overwrite newEloquentBuilder function in Class Model:

   //hacking searchable pagination
    public function newEloquentBuilder($query)
    {
        return new Builder($query);
    }
Notice that Builder here should be the one you extended in Step 1;

Step 3

use it this way:

```
       $posts_all = Post::search($query)->get();
        $count = count($posts_all);
        $posts = Post::search($query)->orderBy('views', 'desc')->paginate_search(8,$count);
```

**Comment by michaelstivala** [comment] 2015-11-02 09:57
Is a solution for this in the pipeline?

**Comment by 4lun** [comment] 2015-11-04 12:26
Another temporary solution similar to @woodytang, but as a single helper function instead (needs to be included globally in a helpers file of some sorts):

    /**
     * Paginate the given collection.
     *
     * @param \Illuminate\Support\Collection $collection
     * @param int                            $perPage
     * @param string                         $pageName
     * @param int|null                       $page
     *
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    function paginateCollection($collection, $perPage = 15, $pageName = 'page', $page = null)
    {
        $page = $page ?: \Illuminate\Pagination\Paginator::resolveCurrentPage($pageName);
        $path = \Illuminate\Pagination\Paginator::resolveCurrentPath();

        return new \Illuminate\Pagination\LengthAwarePaginator(
            $collection->forPage($page, $perPage),
            count($collection),
            $perPage,
            $page,
            compact('path', 'pageName')
        );
    }

Usage:

    $users = App\User::search($searchQuery)->get();
    $users = paginateCollection($users, 10);

Note that it will retrieve ALL results, and trim the resulting collection.

**Comment by zile-lhs** [comment] 2015-11-22 10:27
@4lun I've tried your solution but I had trouble on initial request (without page parameter), while other results worked fine (with page=2 or page=3 etc.).

So I just changed your usage part to: 
$pageNumber = $request->input('page') ? : 1; 
$users = paginateCollection($users, 10, 'page', $pageNumber);

I don't know how any of these work, I'm new to PHP, but just in case someone tries your solution this might help...

**Comment by mcnub** [comment] 2015-11-27 18:03
Changing 'select' to 'where' in the addBindingsToQuery function seems to work for me.

**Comment by bushbill** [comment] 2015-11-30 09:46
+1

**Comment by EugeneRush** [comment] 2015-12-09 17:03
+1

**Comment by miharbi** [comment] 2015-12-09 20:53
We need to accept the fact this guy don't care this bug, someone knows another packages like this?

**Comment by ampersand** [comment] 2015-12-09 20:55
https://github.com/jarektkaczyk/eloquence

**Comment by kingsloi** [comment] 2015-12-09 20:57
I guess so! I needed a solution quick, so rather than mess around with editing the core, or finding another page - I decided to implement ElasticSearch and haven't looked back since. 

https://github.com/elastic/elasticsearch

**Comment by mydnic** [comment] 2015-12-10 08:22
:+1: @ampersand 
https://github.com/jarektkaczyk/eloquence

**Comment by vladbesson** [comment] 2015-12-11 03:47
+1

**Comment by EugeneRush** [comment] 2015-12-11 14:44
+1
https://github.com/jarektkaczyk/eloquence

**Comment by pvledoux** [comment] 2016-01-25 13:54
+1

**Comment by dotfusion-min** [comment] 2016-01-25 19:03
my solution is 
Controller:
$query = 'search__string=' . $keyword . '&search__bedrooms=' . $bedroom_num . '&search__bathrooms=' . $bathroom_num;
View:
{!! $searched_properties->appends([$query])->render() !!}

**Comment by mseymour** [comment] 2016-03-09 16:46
How may people are going to +1 this until it gets fixed?

**Comment by nicolaslopezj** [comment] 2016-03-09 17:11
@dotfusion-min can you create a pull request?

**Comment by melifes** [comment] 2016-03-11 09:49
+1

**Comment by erayaydin** [comment] 2016-03-13 01:39
:+1:

**Comment by gerardo-junior** [comment] 2016-05-13 17:50
+1

**Comment by jaafarazizi** [comment] 2016-08-02 14:03
+1

**Comment by daizuke** [comment] 2016-08-31 08:35
Try this solution

# SearchableTrail.php
Line 96: scopeSearchRestricted
    **Before**
        $this->mergeQueries($query, $q);
        return $q;

    **After**
        return $this->mergeQueries($query, $q);

Line 340: mergeQueries
    **Before**
        $original->mergeBindings($clone->getQuery());

    **After**
        $original->mergeBindings($clone->getQuery());
        return $original;

**Comment by imcas29** [comment] 2016-09-02 13:38
+1

**Comment by Roadirsh** [comment] 2016-09-02 13:39
+1 👍

**Comment by kingsloi** [comment] 2016-09-02 13:51
Guys, why don't you abandon this package? This bug has been open for 6 months, with no movement. I was great while it lasted, but Laravel 5.3 introduced Scout, and with Scout you can easily use [Algolia]( https://www.algolia.com/) (and their free tier). 

I did the switch the other day, took me less than 30 minutes, and has a bunch more other benefits.

**Comment by Roadirsh** [comment] 2016-09-02 14:02
Sometimes you just can't upgrade your core framework yet because of dependencies or just time. But you can still say that you want a fix for a good old package.

**Comment by kingsloi** [comment] 2016-09-02 15:22
@Roadirsh very true. I was lucky enough to be able to upgrade. I'm sure a few of the people who +1 could probably upgrade, too. Just thought I'd weigh in in case people didn't know about scout/algolia

**Comment by gufoe** [comment] 2016-12-05 17:36
#126 should solve the problem

**Comment by Hyleeh** [comment] 2016-12-05 17:49
omfg thank you!

**Comment by gufoe** [comment] 2016-12-05 22:17
You're welcome! Did you test it? If it works, can you please comment on the pull request so @nicolaslopezj can merge it?

**Comment by Hyleeh** [comment] 2016-12-06 07:10
Yup tested in Laravel 5.2, works like a charm

**Comment by nicolaslopezj** [comment] 2016-12-06 14:17
Fixed by @gufoe

**Closed by nicolaslopezj** 2016-12-06 14:17 UTC
Labels: help wanted
